# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityUrl=http://identityserver:80"
      - "CacheSettings:ConnectionString=redisdb,password=Your_password123"
    ports:
      - 8001:80
    depends_on:
      - feed.api
      - user.api
      - identityserver
      - redisdb

  feed.api:
    container_name: feed.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=redisdb,password=Your_password123"
    ports:
      - 8002:80
    depends_on:
      - redisdb

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=mssqldb;Database=AppDb;User ID=SA;Password=Your_password123"
      - "IdentityUrl=http://identityserver:80"
      - "CacheSettings:ConnectionString=redisdb,password=Your_password123"
    ports:
      - 8003:80
    depends_on:
      - mssqldb
      - redisdb
      - identityserver
      - logstash

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=redisdb,password=Your_password123"
      - "DatabaseSettings:ConnectionString=Server=mssqldb;Database=AppDb;User ID=SA;Password=Your_password123"
    ports:
      - 8004:80
    depends_on:
      - redisdb
      - mssqldb

  mssqldb:
    container_name: mssqldb
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssqldb_data:/var/opt/mssql
      
  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass Your_password123
    volumes: 
      - redisdb_data:/data

  rabbitmq:
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_conf:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  elasticsearch:
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic_data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    container_name: logstash
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"