# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  feed.api:
    image: feed.api
    build:
      context: .
      dockerfile: Services/Feed/Feed.API/Dockerfile

  user.api:
    image: user.api
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: Services/Auth/IdentityServer/Dockerfile

  mssqldb:
    image: "mcr.microsoft.com/mssql/server"

# volumes: 
volumes:
  mssqldb_data:
