# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:80
    depends_on:
      - feed.api
      - user.api
      - identityserver

  feed.api:
    container_name: feed.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8002:80


  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8003:80

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8004:80